apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillcraft-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skillcraft-website
  template:
    metadata:
      labels:
        app: skillcraft-website
    spec:
      containers:
        - name: skillcraft-website
          image: ${DOCKER_USERNAME}/skillcraft-website:${VERSION}
          ports:
            - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: skillcraft-website
spec:
  selector:
    app: skillcraft-website
  ports:
    - protocol: TCP
      port: 80         # Port exposed inside cluster
      targetPort: 9090 # Port container listens on
      nodePort: 30355
  type: NodePort  # Or ClusterIP / NodePort depending on your setup
